import type { ButtonAsset } from './types';

export const buttonAssets: ButtonAsset[] = [
  {
    id: 'orange-3d',
    label: 'Orange',
    note: 'install CTA',
    colorFrom: '#ff9a2f',
    colorTo: '#f45100',
    textColor: '#ffffff',
    shadowColor: '#f45100',
    animation: 'shake',
  },
  {
    id: 'blue-3d',
    label: 'Blue',
    note: 'clean trust',
    colorFrom: '#38bdf8',
    colorTo: '#2563eb',
    textColor: '#ffffff',
    shadowColor: '#2563eb',
    animation: 'pulse',
  },
  {
    id: 'green-3d',
    label: 'Green',
    note: 'health action',
    colorFrom: '#34d399',
    colorTo: '#059669',
    textColor: '#ffffff',
    shadowColor: '#059669',
    animation: 'breath',
  },
  {
    id: 'pink-3d',
    label: 'Pink',
    note: 'lifestyle',
    colorFrom: '#fb7185',
    colorTo: '#e11d48',
    textColor: '#ffffff',
    shadowColor: '#e11d48',
    animation: 'bounce',
  },
  {
    id: 'purple-3d',
    label: 'Purple',
    note: 'premium app',
    colorFrom: '#a78bfa',
    colorTo: '#7c3aed',
    textColor: '#ffffff',
    shadowColor: '#7c3aed',
    animation: 'shine',
  },
  {
    id: 'cyan-3d',
    label: 'Cyan',
    note: 'scan tech',
    colorFrom: '#22d3ee',
    colorTo: '#0891b2',
    textColor: '#ffffff',
    shadowColor: '#0891b2',
    animation: 'shine',
  },
  {
    id: 'red-3d',
    label: 'Red',
    note: 'urgent',
    colorFrom: '#f87171',
    colorTo: '#dc2626',
    textColor: '#ffffff',
    shadowColor: '#dc2626',
    animation: 'shake',
  },
  {
    id: 'gold-3d',
    label: 'Gold',
    note: 'reward',
    colorFrom: '#fbbf24',
    colorTo: '#d97706',
    textColor: '#ffffff',
    shadowColor: '#d97706',
    animation: 'shine',
  },
  {
    id: 'graphite-3d',
    label: 'Graphite',
    note: 'dark CTA',
    colorFrom: '#475569',
    colorTo: '#0f172a',
    textColor: '#ffffff',
    shadowColor: '#0f172a',
    animation: 'pulse',
  },
  {
    id: 'lime-3d',
    label: 'Lime',
    note: 'fresh',
    colorFrom: '#a3e635',
    colorTo: '#65a30d',
    textColor: '#102a12',
    shadowColor: '#65a30d',
    animation: 'breath',
  },
  {
    id: 'sunset-3d',
    label: 'Sunset',
    note: 'summer CTA',
    colorFrom: '#fb7185',
    colorTo: '#f97316',
    textColor: '#ffffff',
    shadowColor: '#ea580c',
    animation: 'bounce',
  },
  {
    id: 'mint-3d',
    label: 'Mint',
    note: 'fresh install',
    colorFrom: '#6ee7b7',
    colorTo: '#10b981',
    textColor: '#083344',
    shadowColor: '#0f766e',
    animation: 'breath',
  },
  {
    id: 'indigo-3d',
    label: 'Indigo',
    note: 'finance tech',
    colorFrom: '#818cf8',
    colorTo: '#4338ca',
    textColor: '#ffffff',
    shadowColor: '#312e81',
    animation: 'pulse',
  },
  {
    id: 'aqua-3d',
    label: 'Aqua',
    note: 'light scan',
    colorFrom: '#67e8f9',
    colorTo: '#0284c7',
    textColor: '#ffffff',
    shadowColor: '#0369a1',
    animation: 'shine',
  },
  {
    id: 'berry-3d',
    label: 'Berry',
    note: 'beauty CTA',
    colorFrom: '#f472b6',
    colorTo: '#be185d',
    textColor: '#ffffff',
    shadowColor: '#9d174d',
    animation: 'bounce',
  },
  {
    id: 'slate-3d',
    label: 'Slate',
    note: 'utility app',
    colorFrom: '#94a3b8',
    colorTo: '#334155',
    textColor: '#ffffff',
    shadowColor: '#1e293b',
    animation: 'pulse',
  },
  {
    id: 'coral-3d',
    label: 'Coral',
    note: 'warm CTA',
    colorFrom: '#fb7185',
    colorTo: '#ef4444',
    textColor: '#ffffff',
    shadowColor: '#dc2626',
    animation: 'shake',
  },
  {
    id: 'night-3d',
    label: 'Night',
    note: 'high contrast',
    colorFrom: '#1f2937',
    colorTo: '#020617',
    textColor: '#f8fafc',
    shadowColor: '#020617',
    animation: 'shine',
  },
];

export function getButtonAsset(id: string) {
  return buttonAssets.find((asset) => asset.id === id) || buttonAssets[0];
}
