import type { ButtonAnimation, HandMotion, LayerSettings, ScanStyle } from './types';

export const defaultLayerSettings: LayerSettings = {
  layerOrder: ['scan', 'asset', 'cta', 'hand'],
  handId: 'hand-08-soft-3d-pointer',
  handMotion: 'tap',
  handX: 64,
  handY: 87,
  handSize: 112,
  handRotation: 0,
  handLocked: false,
  injectHand: true,
  scanStyle: 'ripple',
  scanX: 50,
  scanY: 88,
  scanSize: 136,
  scanRotation: 0,
  scanLocked: false,
  scanSpeed: 1200,
  scanDelay: 0,
  scanLoop: 'loop',
  scanAutoplay: true,
  scanAnimationName: 'Tap Ripple',
  scanScaleStart: 0.65,
  scanScaleEnd: 1.22,
  scanOpacityStart: 88,
  scanOpacityEnd: 0,
  scanOffsetX: 0,
  scanOffsetY: 0,
  injectScan: true,
  ctaText: 'INSTALL NOW',
  ctaX: 50,
  ctaY: 88,
  ctaWidth: 72,
  ctaRotation: 0,
  ctaLocked: false,
  showCta: true,
  buttonAnimation: 'pulse',
  ctaScanGrouped: true,
  assetId: 'heart-pulse-badge',
  assetX: 50,
  assetY: 58,
  assetSize: 116,
  assetRotation: 0,
  assetLocked: false,
  assetSpeed: 1200,
  injectAsset: false,
};

export const scanPresets: Array<{ id: ScanStyle; label: string; note: string }> = [
  { id: 'ripple', label: 'Tap Ripple', note: 'circle under finger' },
  { id: 'face', label: 'Face Scan', note: 'corner scan, no fill' },
  { id: 'ring', label: 'Pulse Ring', note: 'tap target' },
  { id: 'sweep', label: 'Sweep Line', note: 'scan area' },
  { id: 'spotlight', label: 'Spotlight', note: 'focus item' },
  { id: 'border', label: 'Border Scan', note: 'object box' },
  { id: 'spark', label: 'Spark Hit', note: 'tap feedback' },
  { id: 'none', label: 'None', note: 'off' },
];

export const handMotionPresets: Array<{ id: HandMotion; label: string }> = [
  { id: 'tap', label: 'Tap' },
  { id: 'doubleTap', label: 'Double' },
  { id: 'press', label: 'Press' },
  { id: 'bounce', label: 'Bounce' },
  { id: 'swipeX', label: 'Swipe X' },
  { id: 'swipeY', label: 'Swipe Y' },
  { id: 'drag', label: 'Drag' },
  { id: 'shake', label: 'Shake' },
  { id: 'wave', label: 'Wave' },
];

export const buttonPresets: Array<{ id: ButtonAnimation; label: string }> = [
  { id: 'pulse', label: 'Pulse' },
  { id: 'bounce', label: 'Bounce' },
  { id: 'shine', label: 'Shine' },
  { id: 'shake', label: 'Shake' },
  { id: 'breath', label: 'Breath' },
  { id: 'none', label: 'None' },
];

export const recipePresets: Array<{
  id: string;
  label: string;
  note: string;
  layer: Partial<LayerSettings>;
}> = [
  {
    id: 'tap-target',
    label: 'Tap Target',
    note: 'ring + tap + pulse',
    layer: {
      handId: 'hand-08-soft-3d-pointer',
      handMotion: 'tap',
      scanStyle: 'ring',
      buttonAnimation: 'pulse',
      handSize: 112,
      scanSize: 140,
    },
  },
  {
    id: 'real-press',
    label: 'Real Press',
    note: 'real finger + shine',
    layer: {
      handId: 'hand-09-soft-real-tap',
      handMotion: 'press',
      scanStyle: 'spotlight',
      buttonAnimation: 'shine',
      handSize: 122,
      scanSize: 160,
    },
  },
  {
    id: 'swipe-reveal',
    label: 'Swipe Reveal',
    note: 'swipe hand + sweep',
    layer: {
      handId: 'hand-01-soft-swipe-hand',
      handMotion: 'swipeX',
      scanStyle: 'sweep',
      buttonAnimation: 'bounce',
      handSize: 118,
      scanSize: 148,
    },
  },
  {
    id: 'cta-push',
    label: 'CTA Push',
    note: 'lower CTA emphasis',
    layer: {
      handId: 'hand-06-bold-tap-hand',
      handMotion: 'bounce',
      scanStyle: 'spark',
      buttonAnimation: 'shake',
      handX: 50,
      handY: 82,
      scanX: 50,
      scanY: 82,
      ctaX: 50,
      ctaY: 88,
    },
  },
  {
    id: 'heart-pulse',
    label: 'Heart Pulse',
    note: 'pulse ring + press',
    layer: {
      handId: 'hand-09-soft-real-tap',
      handMotion: 'press',
      scanStyle: 'ring',
      buttonAnimation: 'breath',
      handSize: 118,
      scanSize: 154,
      scanSpeed: 980,
    },
  },
  {
    id: 'scan-sweep',
    label: 'Scan Sweep',
    note: 'sweep line + tap',
    layer: {
      handId: 'hand-08-soft-3d-pointer',
      handMotion: 'tap',
      scanStyle: 'sweep',
      buttonAnimation: 'shine',
      handSize: 108,
      scanSize: 152,
      scanSpeed: 1050,
    },
  },
  {
    id: 'spark-hit',
    label: 'Spark Hit',
    note: 'quick tap feedback',
    layer: {
      handId: 'hand-06-bold-tap-hand',
      handMotion: 'tap',
      scanStyle: 'spark',
      buttonAnimation: 'pulse',
      handSize: 116,
      scanSize: 128,
      scanSpeed: 820,
    },
  },
  {
    id: 'double-tap',
    label: 'Double Tap',
    note: 'two tap cue',
    layer: {
      handId: 'hand-11-line-tap-hand',
      handMotion: 'doubleTap',
      scanStyle: 'ring',
      buttonAnimation: 'bounce',
      handSize: 112,
      scanSize: 136,
      scanSpeed: 1120,
    },
  },
  {
    id: 'drag-focus',
    label: 'Drag Focus',
    note: 'drag hand + border',
    layer: {
      handId: 'hand-01-soft-swipe-hand',
      handMotion: 'drag',
      scanStyle: 'border',
      buttonAnimation: 'shine',
      handSize: 118,
      scanSize: 160,
      scanSpeed: 1350,
    },
  },
  {
    id: 'shake-cta',
    label: 'Shake CTA',
    note: 'attention CTA',
    layer: {
      handId: 'hand-06-bold-tap-hand',
      handMotion: 'bounce',
      scanStyle: 'spark',
      buttonAnimation: 'shake',
      handSize: 120,
      scanSize: 132,
      scanSpeed: 900,
      ctaY: 88,
    },
  },
  {
    id: 'wave-guide',
    label: 'Wave Guide',
    note: 'soft guide motion',
    layer: {
      handId: 'hand-10-line-pointer',
      handMotion: 'wave',
      scanStyle: 'spotlight',
      buttonAnimation: 'breath',
      handSize: 110,
      scanSize: 170,
      scanSpeed: 1450,
    },
  },
  {
    id: 'border-lock',
    label: 'Border Lock',
    note: 'object frame scan',
    layer: {
      handId: 'hand-07-classic-pointer',
      handMotion: 'press',
      scanStyle: 'border',
      buttonAnimation: 'pulse',
      handSize: 114,
      scanSize: 158,
      scanSpeed: 1150,
    },
  },
];
