import type { VisualAsset } from './types';

export const visualAssets: VisualAsset[] = [
  {
    id: 'heart-pulse-badge',
    label: 'Heart Pulse',
    note: 'heart beat badge',
    category: 'heart',
    motion: 'pulse',
    value: '86',
  },
  {
    id: 'ecg-wave-line',
    label: 'ECG Wave',
    note: 'heartbeat line',
    category: 'heart',
    motion: 'wave',
  },
  {
    id: 'heart-live-dot',
    label: 'Live Dot',
    note: 'live tracking',
    category: 'heart',
    motion: 'blink',
  },
  {
    id: 'scan-frame-box',
    label: 'Frame Box',
    note: 'color handles',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'frame',
    previewColor: '#7c3cff',
    previewSpeed: 1200,
  },
  {
    id: 'scan-beam',
    label: 'Scan Line',
    note: 'moving beam line',
    category: 'scan',
    motion: 'sweep',
    scanStyle: 'sweep',
    previewColor: '#22d3ee',
    previewSpeed: 1050,
  },
  {
    id: 'scan-reticle',
    label: 'Reticle',
    note: 'target ring',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'face',
    previewColor: '#f97316',
    previewSpeed: 1280,
  },
  {
    id: 'scan-grid',
    label: 'Scan Grid',
    note: 'grid overlay',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-vertical-beam',
    label: 'Vertical Beam',
    note: 'vertical scan line',
    category: 'scan',
    motion: 'sweep',
    scanStyle: 'border',
    previewColor: '#2563eb',
    previewSpeed: 1180,
  },
  {
    id: 'scan-radar-sweep',
    label: 'Radar Sweep',
    note: 'radar pulse',
    category: 'scan',
    motion: 'sweep',
    scanStyle: 'ring',
    previewColor: '#14b8a6',
    previewSpeed: 1020,
  },
  {
    id: 'scan-ripple-tap',
    label: 'Tap Ripple',
    note: 'tap ring pulse',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'ripple',
    previewColor: '#38bdf8',
    previewSpeed: 920,
  },
  {
    id: 'scan-focus-spot',
    label: 'Focus Spot',
    note: 'spotlight glow',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'spotlight',
    previewColor: '#f59e0b',
    previewSpeed: 1320,
  },
  {
    id: 'scan-spark-hit',
    label: 'Spark Hit',
    note: 'quick flash pulse',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'spark',
    previewColor: '#f59e0b',
    previewSpeed: 760,
  },
  {
    id: 'scan-frame-cyan',
    label: 'Frame Cyan',
    note: 'clean frame scan',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'frame',
    previewColor: '#06b6d4',
    previewSpeed: 1120,
  },
  {
    id: 'scan-border-neon',
    label: 'Border Neon',
    note: 'neon border beam',
    category: 'scan',
    motion: 'sweep',
    scanStyle: 'border',
    previewColor: '#10b981',
    previewSpeed: 980,
  },
  {
    id: 'scan-face-amber',
    label: 'Face Amber',
    note: 'amber face lock',
    category: 'scan',
    motion: 'sweep',
    scanStyle: 'face',
    previewColor: '#f97316',
    previewSpeed: 1220,
  },
  {
    id: 'scan-ring-sonar',
    label: 'Ring Sonar',
    note: 'sonar pulse ring',
    category: 'scan',
    motion: 'pulse',
    scanStyle: 'ring',
    previewColor: '#0ea5e9',
    previewSpeed: 940,
  },
  {
    id: 'scan-sweep-lime',
    label: 'Sweep Lime',
    note: 'fast lime sweep',
    category: 'scan',
    motion: 'sweep',
    scanStyle: 'sweep',
    previewColor: '#84cc16',
    previewSpeed: 860,
  },
  {
    id: 'scan-crop-box',
    label: 'Crop Box',
    note: 'photo crop frame',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-photo-frame',
    label: 'Photo Frame',
    note: 'soft image frame',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-corner-lock',
    label: 'Corner Lock',
    note: 'corner markers',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-nutrition-arrow',
    label: 'Scan Arrow',
    note: 'nutrition callout',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-barcode',
    label: 'Barcode',
    note: 'scan barcode',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-food-card',
    label: 'Food Card',
    note: 'nutrition frame',
    category: 'scan',
    motion: 'pulse',
    value: '690',
  },
  {
    id: 'scan-calorie-chip',
    label: 'Calorie Chip',
    note: 'kcal badge',
    category: 'scan',
    motion: 'count',
    value: '690',
  },
  {
    id: 'counter-bpm',
    label: 'BPM Counter',
    note: '86 bpm',
    category: 'counter',
    motion: 'count',
    value: '86',
  },
  {
    id: 'counter-percent',
    label: 'Percent Count',
    note: '94%',
    category: 'counter',
    motion: 'count',
    value: '94%',
  },
  {
    id: 'counter-countdown',
    label: 'Countdown',
    note: '3 2 1',
    category: 'counter',
    motion: 'count',
    value: '3',
  },
  {
    id: 'storage-used-down',
    label: 'Storage Down',
    note: '125 GB to 73 GB used',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Phone Storage',
    value: '125 GB',
    secondaryValue: '73 GB',
    deltaLabel: '-52 GB used',
    fromRatio: 125 / 128,
    toRatio: 73 / 128,
    accentColor: '#ef4444',
  },
  {
    id: 'storage-used-up',
    label: 'Storage Up',
    note: '73 GB to 125 GB used',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Phone Storage',
    value: '73 GB',
    secondaryValue: '125 GB',
    deltaLabel: '+52 GB used',
    fromRatio: 73 / 128,
    toRatio: 125 / 128,
    accentColor: '#f97316',
  },
  {
    id: 'storage-free-up',
    label: 'Free Space Up',
    note: '4 GB to 28 GB free',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Free Space',
    value: '4 GB',
    secondaryValue: '28 GB',
    deltaLabel: '+24 GB free',
    fromRatio: 4 / 128,
    toRatio: 28 / 128,
    accentColor: '#10b981',
  },
  {
    id: 'storage-free-down',
    label: 'Free Space Down',
    note: '28 GB to 4 GB free',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Free Space',
    value: '28 GB',
    secondaryValue: '4 GB',
    deltaLabel: '-24 GB free',
    fromRatio: 28 / 128,
    toRatio: 4 / 128,
    accentColor: '#ef4444',
  },
  {
    id: 'storage-iphone-cache-clean',
    label: 'Cache Clean',
    note: '118 GB to 84 GB used',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'iPhone Storage',
    value: '118 GB',
    secondaryValue: '84 GB',
    deltaLabel: '-34 GB cache',
    fromRatio: 118 / 128,
    toRatio: 84 / 128,
    accentColor: '#ef4444',
  },
  {
    id: 'storage-iphone-media-trim',
    label: 'Media Trim',
    note: '121 GB to 68 GB used',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'iPhone Storage',
    value: '121 GB',
    secondaryValue: '68 GB',
    deltaLabel: '-53 GB media',
    fromRatio: 121 / 128,
    toRatio: 68 / 128,
    accentColor: '#f97316',
  },
  {
    id: 'storage-iphone-free-boost',
    label: 'Free Boost',
    note: '6 GB to 36 GB free',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'iPhone Free Space',
    value: '6 GB',
    secondaryValue: '36 GB',
    deltaLabel: '+30 GB free',
    fromRatio: 6 / 128,
    toRatio: 36 / 128,
    accentColor: '#10b981',
  },
  {
    id: 'storage-iphone-free-drop',
    label: 'Free Drop',
    note: '36 GB to 8 GB free',
    category: 'storage',
    motion: 'count',
    displayStyle: 'metric',
    title: 'iPhone Free Space',
    value: '36 GB',
    secondaryValue: '8 GB',
    deltaLabel: '-28 GB free',
    fromRatio: 36 / 128,
    toRatio: 8 / 128,
    accentColor: '#ef4444',
  },
  {
    id: 'storage-iphone-segmented-clean',
    label: 'iPhone Bar Clean',
    note: 'settings storage breakdown',
    category: 'storage',
    motion: 'count',
    displayStyle: 'segmented',
    title: 'iPhone',
    value: '116.2 GB of 128 GB Used',
    secondaryValue: '95.7 GB of 128 GB Used',
    deltaLabel: 'Apps, iOS, Messages, Media, System Data',
    fromRatio: 116.2 / 128,
    toRatio: 95.7 / 128,
    accentColor: '#ff3b30',
    segments: [
      { color: '#ff3b30', ratio: 0.42, label: 'Apps' },
      { color: '#ff9500', ratio: 0.18, label: 'iOS' },
      { color: '#ffd60a', ratio: 0.11, label: 'Messages' },
      { color: '#34c759', ratio: 0.14, label: 'Media' },
      { color: '#c7c7cc', ratio: 0.15, label: 'System Data' },
    ],
  },
  {
    id: 'storage-iphone-segmented-alert',
    label: 'iPhone Bar Alert',
    note: 'near full warning bar',
    category: 'storage',
    motion: 'count',
    displayStyle: 'segmented',
    title: 'iPhone',
    value: '127.6 GB of 128 GB Used',
    secondaryValue: '118.4 GB of 128 GB Used',
    deltaLabel: 'Apps, Photos, Messages, Media, System Data',
    fromRatio: 127.6 / 128,
    toRatio: 118.4 / 128,
    accentColor: '#ff3b30',
    segments: [
      { color: '#ff3b30', ratio: 0.48, label: 'Apps' },
      { color: '#ff9500', ratio: 0.16, label: 'Photos' },
      { color: '#ffd60a', ratio: 0.10, label: 'Messages' },
      { color: '#32d74b', ratio: 0.12, label: 'Media' },
      { color: '#0a84ff', ratio: 0.06, label: 'Mail' },
      { color: '#c7c7cc', ratio: 0.08, label: 'System Data' },
    ],
  },
  {
    id: 'storage-iphone-segmented-balance',
    label: 'iPhone Bar Balance',
    note: 'balanced category breakdown',
    category: 'storage',
    motion: 'count',
    displayStyle: 'segmented',
    title: 'iPhone',
    value: '103.8 GB of 128 GB Used',
    secondaryValue: '81.3 GB of 128 GB Used',
    deltaLabel: 'Apps, iOS, Photos, Media, System Data',
    fromRatio: 103.8 / 128,
    toRatio: 81.3 / 128,
    accentColor: '#ff9500',
    segments: [
      { color: '#ff3b30', ratio: 0.36, label: 'Apps' },
      { color: '#ff9500', ratio: 0.19, label: 'iOS' },
      { color: '#ffd60a', ratio: 0.09, label: 'Photos' },
      { color: '#34c759', ratio: 0.18, label: 'Media' },
      { color: '#64d2ff', ratio: 0.06, label: 'Mail' },
      { color: '#c7c7cc', ratio: 0.12, label: 'System Data' },
    ],
  },
  {
    id: 'counter-gb-down',
    label: 'GB Down',
    note: '128 GB to 64 GB',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Storage',
    value: '128 GB',
    secondaryValue: '64 GB',
    deltaLabel: '-64 GB',
    fromRatio: 1,
    toRatio: 0.5,
    accentColor: '#ef4444',
  },
  {
    id: 'counter-gb-up',
    label: 'GB Up',
    note: '16 GB to 64 GB',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Free Space',
    value: '16 GB',
    secondaryValue: '64 GB',
    deltaLabel: '+48 GB',
    fromRatio: 0.12,
    toRatio: 0.5,
    accentColor: '#10b981',
  },
  {
    id: 'counter-gb-down-256',
    label: 'GB Down 256',
    note: '210 GB to 96 GB',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Used Space',
    value: '210 GB',
    secondaryValue: '96 GB',
    deltaLabel: '-114 GB',
    fromRatio: 210 / 256,
    toRatio: 96 / 256,
    accentColor: '#ef4444',
  },
  {
    id: 'counter-gb-up-256',
    label: 'GB Up 256',
    note: '18 GB to 72 GB free',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Free Space',
    value: '18 GB',
    secondaryValue: '72 GB',
    deltaLabel: '+54 GB',
    fromRatio: 18 / 256,
    toRatio: 72 / 256,
    accentColor: '#10b981',
  },
  {
    id: 'counter-percent-down',
    label: 'Percent Down',
    note: '94% to 28%',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Usage',
    value: '94%',
    secondaryValue: '28%',
    deltaLabel: '-66%',
    fromRatio: 0.94,
    toRatio: 0.28,
    accentColor: '#f97316',
  },
  {
    id: 'counter-percent-up',
    label: 'Percent Up',
    note: '18% to 82%',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Cleanup',
    value: '18%',
    secondaryValue: '82%',
    deltaLabel: '+64%',
    fromRatio: 0.18,
    toRatio: 0.82,
    accentColor: '#10b981',
  },
  {
    id: 'counter-percent-down-urgent',
    label: 'Usage Down',
    note: '96% to 54%',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Storage Used',
    value: '96%',
    secondaryValue: '54%',
    deltaLabel: '-42%',
    fromRatio: 0.96,
    toRatio: 0.54,
    accentColor: '#f97316',
  },
  {
    id: 'counter-percent-up-gain',
    label: 'Cleanup Gain',
    note: '12% to 66%',
    category: 'counter',
    motion: 'count',
    displayStyle: 'metric',
    title: 'Cleanup',
    value: '12%',
    secondaryValue: '66%',
    deltaLabel: '+54%',
    fromRatio: 0.12,
    toRatio: 0.66,
    accentColor: '#10b981',
  },
  {
    id: 'status-normal',
    label: 'Normal Badge',
    note: 'status chip',
    category: 'heart',
    motion: 'pulse',
    value: 'Normal',
  },
];

export function getVisualAsset(id: string) {
  return visualAssets.find((asset) => asset.id === id) || visualAssets[0];
}
