import type { VisualAsset } from './types';

export const visualAssets: VisualAsset[] = [
  {
    id: 'heart-pulse-badge',
    label: 'Heart Pulse',
    note: 'heart beat badge',
    category: 'heart',
    motion: 'pulse',
    value: '86',
  },
  {
    id: 'ecg-wave-line',
    label: 'ECG Wave',
    note: 'heartbeat line',
    category: 'heart',
    motion: 'wave',
  },
  {
    id: 'heart-live-dot',
    label: 'Live Dot',
    note: 'live tracking',
    category: 'heart',
    motion: 'blink',
  },
  {
    id: 'scan-frame-box',
    label: 'Frame Box',
    note: 'color handles',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-beam',
    label: 'Scan Line',
    note: 'moving beam line',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-reticle',
    label: 'Reticle',
    note: 'target ring',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-grid',
    label: 'Scan Grid',
    note: 'grid overlay',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-vertical-beam',
    label: 'Vertical Beam',
    note: 'vertical scan line',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-radar-sweep',
    label: 'Radar Sweep',
    note: 'radar pulse',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-crop-box',
    label: 'Crop Box',
    note: 'photo crop frame',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-photo-frame',
    label: 'Photo Frame',
    note: 'soft image frame',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-corner-lock',
    label: 'Corner Lock',
    note: 'corner markers',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-nutrition-arrow',
    label: 'Scan Arrow',
    note: 'nutrition callout',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-barcode',
    label: 'Barcode',
    note: 'scan barcode',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-food-card',
    label: 'Food Card',
    note: 'nutrition frame',
    category: 'scan',
    motion: 'pulse',
    value: '690',
  },
  {
    id: 'scan-calorie-chip',
    label: 'Calorie Chip',
    note: 'kcal badge',
    category: 'scan',
    motion: 'count',
    value: '690',
  },
  {
    id: 'counter-bpm',
    label: 'BPM Counter',
    note: '86 bpm',
    category: 'counter',
    motion: 'count',
    value: '86',
  },
  {
    id: 'counter-percent',
    label: 'Percent Count',
    note: '94%',
    category: 'counter',
    motion: 'count',
    value: '94%',
  },
  {
    id: 'counter-countdown',
    label: 'Countdown',
    note: '3 2 1',
    category: 'counter',
    motion: 'count',
    value: '3',
  },
  {
    id: 'status-normal',
    label: 'Normal Badge',
    note: 'status chip',
    category: 'heart',
    motion: 'pulse',
    value: 'Normal',
  },
];

export function getVisualAsset(id: string) {
  return visualAssets.find((asset) => asset.id === id) || visualAssets[0];
}
