import type { VisualAsset } from './types';

export const visualAssets: VisualAsset[] = [
  {
    id: 'heart-pulse-badge',
    label: 'Heart Pulse',
    note: 'heart beat badge',
    category: 'heart',
    motion: 'pulse',
    value: '86',
  },
  {
    id: 'ecg-wave-line',
    label: 'ECG Wave',
    note: 'heartbeat line',
    category: 'heart',
    motion: 'wave',
  },
  {
    id: 'heart-live-dot',
    label: 'Live Dot',
    note: 'live tracking',
    category: 'heart',
    motion: 'blink',
  },
  {
    id: 'scan-reticle',
    label: 'Scan Reticle',
    note: 'target lock',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-food-card',
    label: 'Food Card',
    note: 'box + result',
    category: 'scan',
    motion: 'sweep',
    value: '690',
  },
  {
    id: 'scan-crop-box',
    label: 'Crop Box',
    note: 'photo detect',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-corner-lock',
    label: 'Corner Lock',
    note: 'four corners',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-nutrition-arrow',
    label: 'Arrow Scan',
    note: 'food pointer',
    category: 'scan',
    motion: 'wave',
  },
  {
    id: 'scan-barcode',
    label: 'Barcode',
    note: 'barcode beam',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-photo-frame',
    label: 'Photo Frame',
    note: 'camera frame',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-calorie-chip',
    label: 'Calorie Chip',
    note: 'result chip',
    category: 'scan',
    motion: 'count',
    value: '690',
  },
  {
    id: 'scan-vertical-beam',
    label: 'Vertical Beam',
    note: 'moving beam',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-radar-sweep',
    label: 'Radar Sweep',
    note: 'radial scan',
    category: 'scan',
    motion: 'pulse',
  },
  {
    id: 'scan-grid',
    label: 'Scan Grid',
    note: 'medical scan',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'scan-beam',
    label: 'Scan Beam',
    note: 'moving beam',
    category: 'scan',
    motion: 'sweep',
  },
  {
    id: 'counter-bpm',
    label: 'BPM Counter',
    note: '86 bpm',
    category: 'counter',
    motion: 'count',
    value: '86',
  },
  {
    id: 'counter-percent',
    label: 'Percent Count',
    note: '94%',
    category: 'counter',
    motion: 'count',
    value: '94%',
  },
  {
    id: 'counter-countdown',
    label: 'Countdown',
    note: '3 2 1',
    category: 'counter',
    motion: 'count',
    value: '3',
  },
  {
    id: 'status-normal',
    label: 'Normal Badge',
    note: 'status chip',
    category: 'heart',
    motion: 'pulse',
    value: 'Normal',
  },
];

export function getVisualAsset(id: string) {
  return visualAssets.find((asset) => asset.id === id) || visualAssets[0];
}
